backend:
    name: git-gateway
    branch: main

media_folder:"public/uploads"
public_folder: "/uploads"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/posts"
      create: true
      slug: "{{slug}}"
      fields:
        - { name: "title", label: "Title" }
        - { name: "date", label: "Date", widget: "datetime" }
        - { name: "body", label: "Body", widget: "markdown"}
